# Generated by Django 3.2.4 on 2021-06-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_system', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='room',
        ),
    ]
