# Generated by Django 3.2.4 on 2021-06-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_system', '0004_rename_room_id_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='projector',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'room_id')},
        ),
    ]
