# Generated by Django 3.2.4 on 2021-06-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_system', '0005_auto_20210618_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'room')},
        ),
    ]
